language: node_js
node_js:
  - 7
install:
  - npm install -g postcss-cli
  - npm install -g autoprefixer

language: minimal
# Install Hugo
install:
#  - url=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}')
  - url='https://github.com/gohugoio/hugo/releases/download/v0.64.0/hugo_extended_0.64.0_Linux-64bit.deb'
  - echo $url
  - curl -OLkSs $url
  - sudo dpkg -i hugo*.deb
#  - cd themes/docsy && git submodule update -f --init && cd ../.. && hugo

script:
  - hugo
#  - echo 'lucianozago.com' > public/CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: bjnhur@gmail.com
  name: bjnhur
  local_dir: public
  on:
    branch: master
